### ISSUE TITLE
Can't change chumhandle bc of number

### ISSUE THREAD

**Issue by Junipr1** [Dpeta/pesterchum-alt-servers#103]
When setting my chumhandle, I accidentally put a number at the start. And now, i get a message that says a number isn't allowed. The only options it gives me are to quit or to reconnect. How do I get to a place where I can change it?

**Comment by Dpeta** [comment]
Resolved on Discord.

Starting a handle with a number shouldn't be allowed though, it's against the IRC protocol. Should probably add a rule against that >.>

**Comment by Dpeta** [comment]
Making the first character a digit shouldn't be possible anymore with https://github.com/Dpeta/pesterchum-alt-servers/commit/38651d7ca71bf1a502fdc33704f153f694c9113c.
