### ISSUE TITLE
(WINDOWS 7) Error when sending animated smilies

### ISSUE THREAD

**Issue by cavefishin** [Dpeta/pesterchum-alt-servers#105]
Im running the latest W7+ release (fully updated) and encountered this error when trying to send the :tab: emote. Pressing 'OK' just causes the error to repeat, with the only option being to forcefully close the conversation window _if_ Pesterchum itself doesn't freeze and crash when the error first occurs.
The error in question is shown here:
![tab_crash](https://user-images.githubusercontent.com/116922213/202840356-883a8039-6bb3-45ce-b8df-25817ca75c06.png)

**Comment by Dpeta** [comment]
Oh that is definitely a PyQt5 issue >.>

**Comment by Dpeta** [comment]
The qt6 .value scope changes don't seem to be backwards compatible for some reason

**Comment by Dpeta** [comment]
Does this version fix it? :?c https://github.com/Dpeta/pesterchum-alt-servers/suites/9397191666/artifacts/443367704

**Comment by cavefishin** [comment]
Hello, apologies for no reply (dealing with finals). The link seems to be broken, as I'm getting a "failed to generate URL to download artifact" error. Could you please supply a fresh link so that I can test?

**Comment by Dpeta** [comment]
Valid 🙏

The artifact expire time is set to a week, so the previous link probably got deleted. Here's a new run: [win7+](https://github.com/Dpeta/pesterchum-alt-servers/suites/9681534761/artifacts/463578242) [w10+](https://github.com/Dpeta/pesterchum-alt-servers/suites/9681534761/artifacts/463578243)

**Comment by Dpeta** [comment]
The commit is included in the v2.5.1 release as well: https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.5.1

**Comment by cavefishin** [comment]
Excellent! I tested the win7 link you posted, and so far by testing with the :tab: emote I now have no crashes. Thank you for the fix!
