### ISSUE TITLE
Certificate Validation Failing on Windows 10, followed by versioning error

### ISSUE THREAD

**Issue by pleonasticTautology** [Dpeta/pesterchum-alt-servers#106]
i'm making this issue on behalf of my partner system. we're trying to get pesterchum running on their Windows 10 64-bit system and, whether via the pre-compiled version or running from source via the command line, the following happens:

1) several "certificate has expired (10)" errors
2) after all of those, it fails for an "[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)" error.

we're unsure how to proceed from here.

- alphy adams-tautology

**Comment by Dpeta** [comment]
Think you saw in the discord but yeah it's an issue some ppl are having for some reason, seems like some window installations might not have the required root certificate to validate irc.pesterchum.xyz's letsencrypt certificate.

That's what seems likely at least, I'm still not fully certain. If that's the case then it's weird that it says it 'expired' as the error message.

Exclusively using the bundled certifi provided certificates seems to fix it though, so I might try & just only use those for the next patch. That has some drawbacks, like the cert bundle not automatically updating, but it's probably preferable to certificate validation just not working for some people.

**Comment by Dpeta** [comment]
Could ny'all test if the most recent commit fixes it? :?c

Artifact build link (requires a github account to download): https://github.com/Dpeta/pesterchum-alt-servers/suites/10019575843/artifacts/486886004

**Comment by Dpeta** [comment]
Alternatively; does the most recent build fix this? :?c

https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.5.3

**Comment by pleonasticTautology** [comment]
> Alternatively; does the most recent build fix this? :?c
> 
> https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.5.3

this works! thanks :D
