### ISSUE TITLE
It keeps saying my username is taken even though i was the one who created the username

### ISSUE THREAD

**Issue by 0SolarFlare** [Dpeta/pesterchum-alt-servers#109]
![fmlpesterchum](https://user-images.githubusercontent.com/121783853/210197807-92b73a4d-ce79-46f8-9bcd-e873820f14e3.png)
It allowed me to use the username jovialContent but I just exited the app and then when I tried to get back in and hit "select profile" it said I could not select it because "jovialContent is already being used"

When I go to delete the profile it says "there was an error deleting this profile"

**Comment by Dpeta** [comment]
Presumably Pesterchum is still open in the background and the profile is still in use, it minimizes when you press the 'x'.
