### ISSUE TITLE
transfer memo ownership

### ISSUE THREAD

**Issue by Nasko-5** [Dpeta/pesterchum-alt-servers#113]
is it possible to transfer the ownership of a memo to someone else?
if not, would it be possible to implement somehow?

**Comment by Dpeta** [comment]
With ChanServ you can transfer ownership via ``SET FOUNDER``, or set a successor with ``SET SUCCESSOR``.

**Comment by Dpeta** [comment]
![image](https://user-images.githubusercontent.com/69427753/216720942-42c89f09-37d3-4f9a-b847-d3fdf5239b6c.png)
