### ISSUE TITLE
NickServ and ChanServ can't recognise any commands, including their help commands

### ISSUE THREAD

**Issue by Weyverling** [Dpeta/pesterchum-alt-servers#114]
Every time I try to type what either NickServ or ChanServ say is their help command it spits out this message: 
"[04:34] NS: Unknown command /msg NickServ HELP. "/msg NickServ HELP" for help." / "[04:41] CS: Unknown command /msg ChanServ HELP. "/msg ChanServ HELP" for help."
I don't have any quirks made up on the account so I don't know where the  is coming from. It happens with just /help(/HELP) while I'm pestering them directly too. I'm not sure if it's a perms issue or something or what.

**Comment by Dpeta** [comment]
``/msg nickserv help`` just means you have to message ``help`` to nickserv, ``/msg`` is a command to send a message that's present in a lot of IRC clients, but in Pesterchum you can just message them directly.

Like so:
![image](https://user-images.githubusercontent.com/69427753/218312298-7f8af759-843c-4d41-9fe4-a86feb5e3463.png)


Think � is a replacement character for a character that failed to decode, maybe your client can't decode utf-8 characters? Are you running an old version? It's not relevant to being able to type ``help`` though.

**Comment by Weyverling** [comment]
Thank you for helping me with this. I tried it with /help I think instead of just "help" and since that gave the same message as the full /msg help (and the /msg help didn't do anything when I tried it in a memo w/o op priv) I thought the bot was broken instead.

**Comment by Dpeta** [comment]
You shouldn't run it from a zip file but that wouldn't effect encoding. Not rly important either way though.
