### ISSUE TITLE
Add Twitch IRC Support

### ISSUE THREAD

**Issue by nyancrimew** [Dpeta/pesterchum-alt-servers#115]
requirements appear to be setting the password and getting capabilities, twitch irc is documented quite well in their docs at https://dev.twitch.tv/docs/irc/authenticate-bot/

**Comment by Dpeta** [comment]
holy glubbing bingle,,

Twitch support would definitely be possible & silly, I've actually played around with it a bit before ![image](https://cdn.discordapp.com/emojis/754639802267074590.webp?size=44&quality=lossless)
![image](https://user-images.githubusercontent.com/69427753/218327829-1ae7109c-fb91-430b-ba7b-623cbe743e0b.png)

**Comment by Dpeta** [comment]
Added a PASS field & twitch.tv/membership cap req with https://github.com/Dpeta/pesterchum-alt-servers/commit/14935a23ce9bc5de17e36677cbe248461d7fa8b1 & https://github.com/Dpeta/pesterchum-alt-servers/commit/da8e6ddbf7af0ee3cc4222875ebfa67a79c61dca, not actual proper support but seems to work given that:

 - oauth pass scope has ``chat:edit+chat:read+whispers:read+whispers:edit``
 - nick/handle is identical to twitch name
 - any channels joined are lowercase

**Comment by Dpeta** [comment]
Added an IRC compatibility option to stop Pesterchum from sending it's silly syntax & an option to force messages to have initials, so twitch!pchum/irc!pchum ought to be more usable now :3 (https://github.com/Dpeta/pesterchum-alt-servers/pull/120 + https://github.com/Dpeta/pesterchum-alt-servers/commit/a7f266c3822413a696f005136f3adb7e2966063a)

![itworks11](https://user-images.githubusercontent.com/69427753/219779358-5edf0f9f-4008-4382-bfa7-811aad3e6440.png)
![itworks22](https://user-images.githubusercontent.com/69427753/219779350-bf23d684-92a6-4b75-9131-ab1b392b0e6b.png)

![wooyeahwooyeah](https://media.discordapp.net/attachments/994009105029148695/996860996821983353/woo_yeah_woo_yeah.gif)
