### ISSUE TITLE
Can't open program

### ISSUE THREAD

**Issue by wormbrains** [Dpeta/pesterchum-alt-servers#12]
![Skjermbilde 2021-01-15 kl  22 21 26](https://user-images.githubusercontent.com/77513231/104780192-afb16100-5780-11eb-9d46-db61a86a7014.png)

I'm on mac. Whenever I try to open it I just get this message. Is there anything I can do?

**Comment by Dpeta** [comment]
Ah, well you're the first person to have tried that build that I'm aware of, actually :0c Is there any way you could maybe give me any kind of more comprehensive error message? I don't have much to go off here.
And, well, if all else fails you could use macports to build the dependencies manually and just run it uncompiled.

**Comment by wormbrains** [comment]
I have to admit I have no idea how this works - I just downloaded the file and opened it. When I open the console this is the first thing it says. There are a lot of messages so I'm not sure what to look for,, Other than that I have no clue how to build dependencies or run it uncompiled :') Let me know if there's anything more specific I should look for in the console!

![Skjermbilde 2021-01-16 kl  12 12 05](https://user-images.githubusercontent.com/77513231/104810363-4cf9ad00-57f4-11eb-9023-c12a8edcc176.png)
![Skjermbilde 2021-01-16 kl  12 12 42](https://user-images.githubusercontent.com/77513231/104810365-4ec37080-57f4-11eb-9b26-a3a736ff6dde.png)
![Skjermbilde 2021-01-16 kl  12 12 18](https://user-images.githubusercontent.com/77513231/104810367-508d3400-57f4-11eb-91b4-1eb499f04095.png)

**Comment by wormbrains** [comment]
Just saw the error section now, sorry! I'm very new to this. Here are the first error messages
![Skjermbilde 2021-01-16 kl  12 17 11](https://user-images.githubusercontent.com/77513231/104810471-0d7f9080-57f5-11eb-9b6f-c396fb930386.png)
![Skjermbilde 2021-01-16 kl  12 17 48](https://user-images.githubusercontent.com/77513231/104810473-12444480-57f5-11eb-9690-0e7d8b8d3ffc.png)
![Skjermbilde 2021-01-16 kl  12 18 01](https://user-images.githubusercontent.com/77513231/104810478-14a69e80-57f5-11eb-92b7-d312b385a403.png)
![Skjermbilde 2021-01-16 kl  12 18 01](https://user-images.githubusercontent.com/77513231/104810480-16706200-57f5-11eb-8140-445d4dbb26cb.png)

**Comment by Dpeta** [comment]
Sorry it took me so long to respond, but I'm still not sure why exactly it doesn't work. I set up a new VM with an older version of macos and made a build on that one instead, and it seems to works on at least one other pc, so maybe you could try that one out. It's under releases as ```Pesterchum-Alt-Mac-1.16.1.zip```.

**Comment by Dpeta** [comment]
Hopefully, the newest build should work, otherwise consider running 1.20 with https://www.winehq.org : )
