### ISSUE TITLE
uh,,,help??? pls????

### ISSUE THREAD

**Issue by kankri69** [Dpeta/pesterchum-alt-servers#13]
i dont know why but this keep showing up??? im not good at this type of stuff so uh, im not sure what to do-

<img width="298" alt="uh" src="https://user-images.githubusercontent.com/78227145/106310203-33635700-6231-11eb-914d-ee5491ea34e5.png">

**Comment by Dpeta** [comment]
Well, it seems to be missing a profile file, perhaps it's referenced in one of the other json files? You could try backing up and then moving/deleting your ```/AppData/Local/pesterchum``` folder. (Make sure to make a backup, as your logs are stored in the same folder.)

**Comment by Dpeta** [comment]
Alright, this should hopefully be fixed now. Could you try and see if the newest release works for you?

**Comment by hvuvty** [comment]
sorry i didnt see this sooner but yes it works!! thank you!!
