### ISSUE TITLE
SSL "Wrong Version Number" Error

### ISSUE THREAD

**Issue by halogeneticist** [Dpeta/pesterchum-alt-servers#130]
When I try to connect to pesterchum.xyz servers, I receive the following error:

` F4IL3D: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c: 997)`

Searching through previous issues, someone got the same error as me, and the fix was installing Pesterchum v.2.5.3, which is the exact version I've been using this whole time. I haven't used the software in a while, but prior to today I had zero problems.

**Comment by Dpeta** [comment]
Wrong SSL version number seems to just get thrown when the SSL handshake fails, so probably just a connection issue, or the server timed you out or smthin for trying to connect too many times too quickly. Issue #106 had to do with certificates, if you're referring to that one, it's unrelated.

Maybe verify you're not behind a school/work firewall that blocks IRC connections.

**Comment by halogeneticist** [comment]
Restarted my system and it was able to connect, although it took a bit longer than normal. I'm guessing my network's firewall is just acting up outta nowhere. Thanks!
