### ISSUE TITLE
group chat/servers?

### ISSUE THREAD

**Issue by boxiecola** [Dpeta/pesterchum-alt-servers#136]
is there any way to create a separate little server for me and friends, or group chats? pesterchum makes it easy to handle quirks and such, so we want to do it on it

**Comment by Dpeta** [comment]
Sure, Pesterchum is an IRC client, so you could set up an IRC server, like [UnrealIRCd](https://www.unrealircd.org/) or [one of the many alternatives](https://www.ircstats.org/servers). Group chats (channels) are already a thing, they're just presented as memos for Pesterchum. If it's mainly for quirks, you could also mybe [bridge a memo to discord](https://github.com/Dpeta/pesterchum-alt-servers/wiki/Bridging-Discord-and-Pesterchum-(with-Matterbridge)) or something.
