### ISSUE TITLE
Can't receive random encounters?

### ISSUE THREAD

**Issue by jackCzoklet** [Dpeta/pesterchum-alt-servers#14]
For some reason I can't tick the option 'receive random encounters' at all. Like it's blocked
![aaaaa](https://user-images.githubusercontent.com/78379003/106504816-bd2c5200-64c7-11eb-871c-8859009ab571.png)

**Comment by Dpeta** [comment]
It's that way for everyone. The randomEncounter bot sadly isn't on the server, so random encounters currently don't work. Someone suggested possibly making it client-side in the future, but nothing has come of that as of yet :(

**Comment by Dpeta** [comment]
We're now running something akin to the old RE bot, so it should hopefully work now :3c
