### ISSUE TITLE
pesterchum wont open

### ISSUE THREAD

**Issue by FIVEGEAR5** [Dpeta/pesterchum-alt-servers#144]
yo
im trying to open pesterchum, but whenever i try to access pesterchum.exe, it says that the smilies folder is not found even though i already have it downloaded
does anyone have a solution to this

**Comment by Dpeta** [comment]
Most likely you either:
1. Didn't extract the zip-file.
or
2. Moved the .exe to a different folder like your desktop instead of making a shortcut.

**Comment by FIVEGEAR5** [comment]
thanks
ill try both of these to see if one of them is the issue
