### ISSUE TITLE
Alternian Font tags <alt></alt> don't work

### ISSUE THREAD

**Issue by ThePixelist** [Dpeta/pesterchum-alt-servers#147]
When I put text in the tags `<alt>like this</alt>`, nothing happens. Other tags like `<c>` work fine. Tested in quirk testing thingy and chat.

**Comment by Dpeta** [comment]
Are you sure you're actually a running a version that has alt tags? There haven't been any releases since those commits.

**Comment by Dpeta** [comment]
Closing since there was no follow-up, assuming this was just a wrong version thing
