### ISSUE TITLE
Can't get into accounts listed??

### ISSUE THREAD

**Issue by adamesmerised** [Dpeta/pesterchum-alt-servers#148]
drk how to title this, but like, it says "pick a profile" but when i try to pick an account listed that I made and used it says that it's a taken username and then doesnt let me in. how sad :( maybe i just dont know how to use pesterchum though ajdskwqjfvks

**Comment by Dpeta** [comment]
Only one person can be on a handle/nick at the same time on a server, profiles are strictly local and don't reserve the right to use the associated handle. Either someone else is on that handle currently or maybe you have two instances of Pesterchum open.
