### ISSUE TITLE
regexp quirk crashes pesterchum?

### ISSUE THREAD

**Issue by vivibeepboop** [Dpeta/pesterchum-alt-servers#149]
i have a regexp quirk that makes my text colour alternate from red to blue with each letter and when i try to send longer messages, pesterchum just crashes.

**Comment by Dpeta** [comment]
Could you check if you're running the most recent version & if there's any error logs? Was there not a msg box popup with an exception?

**Comment by Dpeta** [comment]
closing since there was no follow-up
