### ISSUE TITLE
The problem with the lack of servers when choosing.

### ISSUE THREAD

**Issue by nazoReken** [Dpeta/pesterchum-alt-servers#151]
Good day, dear developers. My friend ran into a problem. When choosing a server to connect to, she does not have any servers and only has a choice between adding a server and removing it. Could you tell me how to solve it?
![image](https://github.com/Dpeta/pesterchum-alt-servers/assets/142545024/d0d98722-13e1-40b7-86ba-4e3b5a24df20)

**Comment by Dpeta** [comment]
Address for the default server is irc.pesterchum.xyz:6697 (with SSL/TLS), if you want to add it again.
