### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by Murritloll** [Dpeta/pesterchum-alt-servers#152]
Giant confusion, whenever im switching profiles to another profile i use (ecoParadox) it tells me it is taken but i literally just logged into it

**Comment by Dpeta** [comment]
Multiple sessions can't use the same nick/handle at the same time. If it says your handle is taken you might still have another instance of Pesterchum open in the background.

**Comment by Murritloll** [comment]
> Multiple sessions can't use the same nick/handle at the same time. If it says your handle is taken you might still have another instance of Pesterchum open in the background.

damn thanks

**Comment by Murritloll** [comment]
also i realized i did cuz i never closed them i just minimized em without knowing
