### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by Gloopyperson** [Dpeta/pesterchum-alt-servers#158]
Just downloaded the program and closed it to test something, but when I reopened it now it says my own accounts username is taken and I don't know how to fix it
![image_2023-09-26_182944649](https://github.com/Dpeta/pesterchum-alt-servers/assets/146146149/b04c2eec-a8fa-43bc-9f9e-0e18c5e48154)
![image_2023-09-26_182955597](https://github.com/Dpeta/pesterchum-alt-servers/assets/146146149/8e1b62f6-9a3e-4cc5-9563-21a68a191e4a)

**Comment by Gloopyperson** [comment]
it fixed it self after a few hours

**Comment by Dpeta** [comment]
it was probably just still open in the background
