### ISSUE TITLE
que2tiion

### ISSUE THREAD

**Issue by ThePixelist** [Dpeta/pesterchum-alt-servers#16]
my dude
what on EARTH happened
iive had pe2terchum open for the pa2t few month2 everyday day && got one random encounter
now over the cour2e of 2 day2 iive gotten liike, 4
thii2 ii2nt a complaiint iit2 iincrediible actually but liike
how man‽
diid 2ome famou2 per2on reviie2 pe2terchum or 2omethiing

**Comment by Dpeta** [comment]
Well that's probably because random encounters were broken until a few days ago uwu
