### ISSUE TITLE
 "this handle is already taken!" 

### ISSUE THREAD

**Issue by crystallineConfectioner** [Dpeta/pesterchum-alt-servers#173]
My default profile was not saved when I clicked "default profile" which caused Pesterchum to say that it was already taken. This is constant recurrence and it quite frustrating.

**Comment by crystallineConfectioner** [comment]
![image](https://github.com/Dpeta/pesterchum-alt-servers/assets/84612696/ccae5b1a-8e6a-4818-9882-a51f05a6bc1d)

**Comment by Dpeta** [comment]
![taken](https://github.com/Dpeta/pesterchum-alt-servers/assets/69427753/4ee84761-17ad-4f82-a635-2c8581793436)

**Comment by darkst0rm223** [comment]
lmao
