### ISSUE TITLE
yoooo uh help it wont open

### ISSUE THREAD

**Issue by dstri25** [Dpeta/pesterchum-alt-servers#18]
yo hey first of all i gotta say thanks for running a new pesterchum program! after the last one shut down i was glad to hear there's a new one 

anyway i uhh had a problem with the application that i downloaded? dont let the dirk theme fool you i have no idea how code and stuff works i just downloaded the file and opened it

but uh anyway. im currently on a mac and have been trying to run the app but only this is popping up 

![Screen Shot 2021-03-09 at 5 02 00 PM](https://user-images.githubusercontent.com/80368775/110559784-b2ce2b00-80f9-11eb-816b-2e67288078ce.png)

when i clicked open console, the following showed up 

![Screen Shot 2021-03-09 at 5 06 47 PM](https://user-images.githubusercontent.com/80368775/110559899-e315c980-80f9-11eb-98bd-b985762a9fbf.png)

im not exactly sure what the problem is and if its a problem with pesterchum itself or my own computer but i could use some advice haha 

quick edit: oh yeah, forgot to mention: i downloaded the most recent issue, so *checks* yeah i downloaded Pesterchum-Alt-Mac-1.20.zip

**Comment by Dpeta** [comment]
Ah :(
I'm sorry about that, it's almost certainly an issue with Pesterchum, the mac build isn't, well, completely functional- It seems to work on some computers, but not on others, and I'm not entirely sure why :(
If all else fails, you could try running the windows version with wine https://www.winehq.org/, since that seems to be a lot more functional.

**Comment by dstri25** [comment]
ah shoot sorry for not replying to this earlier!! 
thats alright, ill try out the windows version, thank you for the advice :)

**Comment by Dpeta** [comment]
Alright! :+1:
The most recent mac build is now also something you could try : )
