### ISSUE TITLE
Random Encounters Disabled?

### ISSUE THREAD

**Issue by garbledArtist** [Dpeta/pesterchum-alt-servers#182]
I've been unable to turn on or use Random Encounters, both in options and in the client dropdown.
I don't think it is a general issue with the bot, as multiple of my friends have had it actively working while this is happening.

When I go to use it, it is grayed out in both areas, and I can't click them to turn it on
![image](https://github.com/user-attachments/assets/9ba3209a-fafe-4ada-b319-e6d716876757)
![image](https://github.com/user-attachments/assets/a9ecabbb-592a-4ab7-bfaf-f4cc6ded6c1b)

Any help on this would be greatly appreciated, I've been really wanting to use the feature

**Comment by Dpeta** [comment]
Is IRC compatibility mode turned on maybe?

**Comment by garbledArtist** [comment]
It was, This fixed my issue, thank you!

**Comment by Dpeta** [comment]
![woo_yeah_woo_yeah](https://github.com/user-attachments/assets/6d49cf5c-0059-4b95-b638-d878dbb7d047)
np o7
