### ISSUE TITLE
Windows: animated smilies not displaying

### ISSUE THREAD

**Issue by frogwoosh** [Dpeta/pesterchum-alt-servers#19]
The Windows (64-bit) release is unable to properly display the animated smilies. Instead a missing file icon is shown.

**Comment by Dpeta** [comment]
Hmm,,, oddly enough, it seems to work for me on linux, but when I run the windows version with wine it does indeed show a missing file, even though the file does seem to be present. It's probably something with my build being broken again, I'll try to get around to taking a look at it soon.

**Comment by Dpeta** [comment]
This should be fixed now :)
