### ISSUE TITLE
Program keeps randomly crashing

### ISSUE THREAD

**Issue by Tolpen** [Dpeta/pesterchum-alt-servers#20]
What it says on the tin: the app (on Windows 10) keeps randomly shutting down. So far it has only happened to me when I was pestering someone. I had to open the app and connect again. I do not know what could have caused it or what information would be useful.

**Comment by Dpeta** [comment]
Yeah, I think it has something to do with someone spamming unicode characters in pesterchum's mood channel, the client's unable to decode them and crashes. It should hopefully be fixed now, I'll put up a release in a minute.

**Comment by Dpeta** [comment]
Or, well, them being unicode characters wasn't the issue, it was pesterchum being unable to decode them for some reason. Hopefully it should be fixed now.
