### ISSUE TITLE
Super annoying issue...

### ISSUE THREAD

**Issue by totalTremor** [Dpeta/pesterchum-alt-servers#21]
When i close pesterchum using the X or closing all tabs, if i click on it again it will open a completely separate pesterchum client from mine. example: username totalTremor, close window, click on pesterchum in the toolbar to open it, username Pesterclient223 
if i uninstall it might fix but i don't want to lose my profile, any help? the only way to get back into totaltremor's profile once pesterclient's is open is to close all instances through task manager... 
edit: I was wrong, every single time i open pesterchum, if it was opened previously it will open it in a new account each time. (pesterclient345, pesterclient8774, etc.)
![image](https://user-images.githubusercontent.com/81880404/113490577-33c5db80-9488-11eb-8761-6d476c83ab89.png)

**Comment by Dpeta** [comment]
I think the 'X' just causes Pesterchum to be minimized, so it will most likely have just moved to your system tray, you should close it either from the tray or via client ---> exit, and there are also options under "Interface" in settings to change this behavior. Does that fix your issue?

**Comment by Dpeta** [comment]
Try closing Pesterchum like this: ![Screenshot_20210419_120005](https://user-images.githubusercontent.com/69427753/115219418-0a978300-a0f7-11eb-8215-67d7a170324a.png) or this: ![Screenshot_20210419_120046](https://user-images.githubusercontent.com/69427753/115219405-08cdbf80-a0f7-11eb-8a0d-1b5ed2e932bb.png) if you don't want it to minimize :3
