### ISSUE TITLE
Colors don't work properly or something like that

### ISSUE THREAD

**Issue by CostaCiruela** [Dpeta/pesterchum-alt-servers#24]
So, since I updated Pesterchum to the version released yesterday, me and my friends see the text colors (even the chumhandle) of each others only black. We see the correct colors in the memos, but not in the normal chats.

This didn't happen before, I have more old versions and works fine without this issue.

Sorry about my bad english btw.

**Comment by Dpeta** [comment]
That,,, does seem to be the case, I guess I just never noticed it before- jsdhfjsdhfj
For some reason, ``irc.colorUpdated`` & ``widget.updateColorSlot`` weren't being returned by ``ircQtConnections``, so, I don't understand why it was working at all before.
It should hopefully be fixed now though, if not, please open a new issue :3c
