### ISSUE TITLE
Color *and* name issue

### ISSUE THREAD

**Issue by asterArmageddon** [Dpeta/pesterchum-alt-servers#27]
I'm more upset with the color issue. Outside of memos, noone's color accept mine shows up in chat. They can see my color, but they all show up as black and its upsetting... I can mostly deal with the name issue, if I close a pchum tab and try to sign back in it won't let me because my name is "taken" (and no I do not use canon handles) but this goes away if I turn my pc off and on again. or wait several hours. i can also just make a double accy anyway. just plz.... want color fix it's been bothering me for several days since I downloaded the thing.

**Comment by Dpeta** [comment]
Hopefully 730a352 should make this a bit less confusing :'3 (and fix Pesterchum not shutting down correctly when it's closed like this: 
![Schermafbeelding 2021-04-20 190645](https://user-images.githubusercontent.com/69427753/115436719-d311ff00-a1fa-11eb-8e55-65d3cc4073ea.png)
)

**Comment by asterArmageddon** [comment]
Yes, that does indeed check out, I am stuck on v2.0.2 and do not have the update, having downloaded the client on 4/2/21? I am very, very not tech-savvy, do I need to download it again?? And, if yes, do I also have to get rid of the prior version?? Also yea, I just realized that the taken name issue is totally discussed on the website. Sorry bout that. 
![Screenshot (12)](https://user-images.githubusercontent.com/82853026/115948228-c6530c80-a481-11eb-9b0d-4ed49fdda154.png)

**Comment by Dpeta** [comment]
Yeah, you just need to download it again. And you might as well get rid of the previous version, too, though that's not required.
And no worries uvu
