### ISSUE TITLE
user 

### ISSUE THREAD

**Issue by carniiv0r0u2Tactiiciian** [Dpeta/pesterchum-alt-servers#33]
when i opened  the  program the first time it leet me use carniiv0r0u2Tactiiciian as my tag but when i re opened it it didn't allow me to use  the tag

**Comment by Dpeta** [comment]
Are you sure it wasn't minimized to your tray? Without any further info I can't really help you úwù
Maybe try closing Pesterchum like this in the future:
![115218962-978e0c80-a0f6-11eb-86cd-4956a4a1ad00](https://user-images.githubusercontent.com/69427753/118317718-eeb1b200-b4e7-11eb-804c-3816f0ef8269.png)
