### ISSUE TITLE
PyQt5 and ostools won't install

### ISSUE THREAD

**Issue by necropurity** [Dpeta/pesterchum-alt-servers#34]
after learning how to work python, download pip and install python dependencies, ive come to a solid bust that is:

"ERROR: Could not find a version that satisfies the requirement PyQt5 (from versions: none)
ERROR: No matching distribution found for PyQt5"

and

"ERROR: Could not find a version that satisfies the requirement ostools (from versions: none)
ERROR: No matching distribution found for ostools"

everything else was able to be installed, and running "python pesterchum.py" doesn't work so im at a complete loss here

im not very tech savvy, so im glad i even managed to get to a point, but now im just discheesed that i cant get in. not to mention im on a mac so everytime i try to directly open the only file that says pesterchum, my damned macOS stuff keeps blocking things they cant verify so that blows

**Comment by Dpeta** [comment]
Are you certain you're running Python 3 and not Python 2? That could be one reason why it can't find the distributions. You could make sure you're running the correct version with ``python --version``. Or perhaps you have multiple versions of Python installed? In that case you could make sure you're running the correct pip with ``pip3`` or ``python3 -m pip``, if that's available on your system.
