### ISSUE TITLE
Emotes and Quirks

### ISSUE THREAD

**Issue by sokoAwen** [Dpeta/pesterchum-alt-servers#35]
If a quirk changes the letters in an emote, then the emote doesn't work, although not sure how easily fixable that is. Maybe some sort of blacklist for all the emote strings? Still loving the program though!! :DD

**Comment by Dpeta** [comment]
That would certainly be something useful to look into :0c

**Comment by Dpeta** [comment]
Added an option to exclude emotes from quirks in 2a413dcc891692275b3e9fefec34b55e92f29792.

My solution here was basically to:
1. Make a list of breakable strings (like emotes).
2. Split the input into non-breakable and breakable.
3. Run every non-breakable substring individually through the quirk.
4. Reconstruct the string.

**Comment by Dpeta** [comment]
Closing since the exclude option seems to work decently enough
