### ISSUE TITLE
mac issues

### ISSUE THREAD

**Issue by aradeeea** [Dpeta/pesterchum-alt-servers#37]
hello! i’m a mac user (unfortunately) and haven’t been able to get a windows device yet. i have tried downloading the latest mac version, but when i do so, it just puts a file on my computer, not an application. i’ve gone into the file and opened the script called “pesterchum” but everytime i open it, my mac needs something allowed, even if it’s the same thing over and over again. i’ve allowed every single thing it’s requested, and even opened and allowed other scripts in the file, but nothing seems to work. i’m not sure if there’s a fix to this, but i’d like to see anyways!!

**Comment by Dpeta** [comment]
The mac builds are sadly a bit of a hack- An alternative way to run Pesterchum would be by simply installing Python, downloading the repository, and running ``pesterchum.py`` directly. (The dependencies can be installed via pip and are in the README)

**Comment by Dpeta** [comment]
The new macOS releases have been reported to work, please open a new thread if they still don't :3👍
