### ISSUE TITLE
so uh this error keeps coming up whenever i try and open it.

### ISSUE THREAD

**Issue by adepressedtowel** [Dpeta/pesterchum-alt-servers#38]
ive had pesterchum for a few months now and this is the first time that its broken. ive tried re downloading it a few times and it still hasnt changed
![image](https://user-images.githubusercontent.com/86267278/122845717-a50a8180-d347-11eb-8cc6-f19a6d087f20.png)

**Comment by Dpeta** [comment]
Hmmm, I'm guessing it's an issue with your ``pesterchum.js`` file? That,,, seems to be quite common ÓvÓ
It should be in ``appdata/local/pesterchum/``. You could try moving it somewhere else so it'll remake it.

Making an actual proper fix for the constant json issues is definitely something I should get around to.

**Comment by thev216** [comment]
i'm having the same problem but this is the first time i opened the program, i first downloaded it manualy but after a bunch of  errors and shenanigans with Microsoft Visual Studio package .dlls i had to to correct all those errors. then i was met with this:
![Captura](https://user-images.githubusercontent.com/84483419/124330808-2938e200-db5c-11eb-8f17-955ce8feda57.PNG)

I tried installing it with the installer instead and is still the same 

Also, i checked `appdata/local/ `and there is not a pesterchum folder anywhere

**Comment by Dpeta** [comment]
Sorry for my late response-
Are you running windows 7? If so that version of Pesterchum might not be compatible, so you might want to try the most recent version.

**Comment by arachnoLover** [comment]
This is the first time i am trying to launch the programm, and this is the latest pchum version. Also no pchum folder at AppData.
![Screenshot_2](https://user-images.githubusercontent.com/91280519/134553081-c2fd4e89-e88d-440c-b939-27907ba1107e.png)

**Comment by Dpeta** [comment]
Ah- I think I missed your msg, sorry- If anyone here is still having issues months later mybe making your own thread or joining the support server would be more productive
