### ISSUE TITLE
no idea

### ISSUE THREAD

**Issue by catwow22** [Dpeta/pesterchum-alt-servers#39]
im new to pesterchum, my friend made me get it like just the other day so pardon me if i have no idea what im talkin' abput. 
every time i relaunch pesterchum it says my name 'tenebrousTentacle' was taken. it was working just fine when i got it. and it does this every time i open it again.

**Comment by Dpeta** [comment]
Most likely, another instance of Pesterchum was still running. It may have been minimized, or it may have been some sort of bug. Maybe try exiting out of Pesterchum via ``CLIENT ---> EXIT``.

Alternatively, look into registering your handle with nickserv so you can just reclaim your handle in the future (guide: https://squidmaid.tumblr.com/post/67595522089/how-to-register-your-pesterchum-handle-the-actual )
