### ISSUE TITLE
pls help i cant use my handle :(

### ISSUE THREAD

**Issue by secretsolitaire** [Dpeta/pesterchum-alt-servers#44]
i closed pesterchum and now it wont let me use my handle, every time i try it tells me my handle is already in use :(

![Pesterchumissue](https://user-images.githubusercontent.com/87445726/125679148-ab27debf-7a92-4f33-97f5-d57541f28b71.PNG)

**Comment by revengerights** [comment]
im getting the same one :((

**Comment by secretsolitaire** [comment]
fdjgjgkljgfkljhf im having this issue now :/

![image](https://user-images.githubusercontent.com/87445726/125853763-5c279800-3439-483e-923d-9e880ab935d9.png)

**Comment by Dpeta** [comment]
Yeah, if your handle is taken that'll most likely be because pchum is still running in the background :0c

**Comment by Dpeta** [comment]
> fdjgjgkljgfkljhf im having this issue now :/
> 
> ![image](https://user-images.githubusercontent.com/87445726/125853763-5c279800-3439-483e-923d-9e880ab935d9.png)
> ok i fixed it there were like ten open pesterchums in my tray-

[SSL: WRONG_VERSION_NUMBER] is a generic connection error that can appear for loads of reasons, but yeah, having 10 pchums ovep could've very well been the reason, since the server limits the amount of connections from a single IP (it's a reasonable number though, dw :3 )
