### ISSUE TITLE
full on broke

### ISSUE THREAD

**Issue by Ooferzman** [Dpeta/pesterchum-alt-servers#47]
so my pester chum completely broke on me and didn't let me access anything saying it could not connect to the username and now i need to get back to my account and need help

**Comment by MrMoony05** [comment]
I'm having the same issue.

**Comment by Dpeta** [comment]
I'm sorry but, that's not very specific- So I'm not sure how much help I can be here. The server is still up without a dip in average users, so it's most likely an issue on your end. I'm also not sure what you mean with "it could not connect to the username and now i need to get back to my account and need help". Do you mean you lost access to a registered handle?

Perhaps you're connecting from behind a firewall? Schools & certain workplaces sometimes block IRC ports. Having your pc's time be very off can also sometimes cause issues with IRC & TLS certificates.
Those are very general tips though- I'm not sure if they're applicable here.

**Comment by Ooferzman** [comment]
yeah i lost access to a registered handle

**Comment by Dpeta** [comment]
Ah, well, you can reset your password with the ``resetpass`` command
