### ISSUE TITLE
my chumhandle

### ISSUE THREAD

**Issue by mascopog** [Dpeta/pesterchum-alt-servers#48]
my chumhandle has been mine since the day i downloaded it, but today it said that my chumhandle has been stolen.

**Comment by Dpeta** [comment]
If you msg me on _turntechCatnip I can kick whoever is on the handle off. (Though you probably just still have pchum open in the background somewhere.)
[Maybe register your handle for next time. ](https://squidmaid.tumblr.com/post/67595522089/how-to-register-your-pesterchum-handle-the-actual)

**Comment by mascopog** [comment]
Right so i solved it.
However i cant tend to the profile, (changing my mood, adding chums, etc) so i made another chumhandle, and it logged me off entirely again. 
I registered myself on nickserv aswell, but it keeps denying me access.
What do i do
