### ISSUE TITLE
again..

### ISSUE THREAD

**Issue by mascopog** [Dpeta/pesterchum-alt-servers#49]
Right so i solved it.
However i cant tend to the profile, (changing my mood, adding chums, etc) so i made another chumhandle, and it logged me off entirely again.
I registered myself on nickserv aswell, but it keeps denying me access.
What do i do

**Comment by mascopog** [comment]
![Screenshot (413)](https://user-images.githubusercontent.com/87970845/127103855-2f512bda-4e45-46d1-89f2-e4127a203a86.png)

**Comment by mascopog** [comment]
![Screenshot (415)](https://user-images.githubusercontent.com/87970845/127103938-6f1804ff-2bbe-4cc1-b59d-a0351e000a00.png)

**Comment by Dpeta** [comment]
If you're registered with nicksev you can message ``recover`` to nickserv to regain control of your handle :0c

**Comment by mascopog** [comment]
Why[image: Screenshot (416).png]
 does it keep telling me access denied?

**Comment by mascopog** [comment]
why does it keep telling me "access denied" [image: Screenshot (416)_LI.jpg]

**Comment by Dpeta** [comment]
Maybe you put in the wrong password? If you forgot your password you can use the ``resetpass`` command to reset it.
Also I think you attached that screenshot wrong úvù

**Comment by Dpeta** [comment]
If you're still unable to access your registration msg me on ``_turntechCatnip`` sometime :0c
