### ISSUE TITLE
whenever i try to log into my chumhandle it dosent let me

### ISSUE THREAD

**Issue by w0rmf00d** [Dpeta/pesterchum-alt-servers#58]
whenever i try to log into my chumhandle (windows) it dosent let me log in and it just changes it to being pestercliet automatically

**Comment by Dpeta** [comment]
What's your chumhandle? :?c
If you registered it then you need to msg ``identify [password]`` to nickserv to log in/authenticate.

**Comment by Dpeta** [comment]
If you forgot your password you can reset it by messaging ``resetpass [handle] [email]`` to nickserv, or wait for the registration to expire (that happens after a few weeks of inactivity/not signing in).
