### ISSUE TITLE
unable to use or switch profiles

### ISSUE THREAD

**Issue by vindictiveWarmonger** [Dpeta/pesterchum-alt-servers#59]
whenever I try to do either of these things, I get the message "Failed to open "C:Users/(name)/AppData/Local\pesterchum/profiles/(username)"

**Comment by Dpeta** [comment]
Not sure what causes that but, you might be able to fix it by making a backup of ``C:Users/(name)/AppData/Local\pesterchum/pesterchum.js`` and ``C:Users/(name)/AppData/Local\pesterchum/profiles/`` and then deleting them, this'll reset your profile though, so things like your chumroll will reset, you could then manually re-add your chumroll from your backup ``pesterchum.js``.

**Comment by Dpeta** [comment]
This error should no longer cause a crash since 8e9b696a1cfd8f2725283a0e75fe7ff5e23488aa.
