### ISSUE TITLE
cx_Freeze error on latest build

### ISSUE THREAD

**Issue by Gilgameshking07** [Dpeta/pesterchum-alt-servers#64]
![image](https://user-images.githubusercontent.com/93661400/140072449-dbd3eae2-98f4-48a9-837f-9df27579f10e.png)
This is the error I just started getting out of the blue. The file has been extracted and I still had the error on a fresh install on a different drive. This message just pops up when I try running the exe

**Comment by Dpeta** [comment]
Fixed over discord so ig I'll just close the issue 🐱
