### ISSUE TITLE
error message please tell me how to fix this

### ISSUE THREAD

**Issue by realestofchariots** [Dpeta/pesterchum-alt-servers#65]
![image](https://user-images.githubusercontent.com/95987099/145694908-5d1c00fb-d57f-4217-ab87-4932365f389e.png)
what do i do

**Comment by realestofchariots** [comment]
i think someone had the same problem but will there be a possibly new version for this being fixed thank you

**Comment by Dpeta** [comment]
I'm guessing pesterchum.js got blanked 💀, not sure why that happens. You can probably fix it by changing its name so it'll reset, it's in /appdata/local/pesterchum/.

I'll try to at least add some kind of fallback soon.

(Feel free 2 join our server https://discord.gg/danXrkcQ for support btw)
