### ISSUE TITLE
tiny??

### ISSUE THREAD

**Issue by cr-3ature** [Dpeta/pesterchum-alt-servers#66]
im not sure if this is an issue with my computer or something, but all of the screens are super small on my end, like eyestrain levels of way too little. everything works fine otherwise. just... tiny.

**Comment by Dpeta** [comment]
What's your screen resolution? :?c

**Comment by cr-3ature** [comment]
2736 x 1824 (which is the recommended resolution on my computer)

**Comment by Dpeta** [comment]
Yeahh, I don't think Pesterchum scales with resolution, so that's probably why 💀. Adding some form of scaling to the client would definitely be useful, though I'm not sure how complicated that'd be-
(you might be able to fix it 4 now by making your resolution lower while using pchum- </3)

**Comment by Dpeta** [comment]
We're running PyQt6 now, so Pesterchum _should_ support scaling: https://doc.qt.io/qt-6/highdpi.html

**Comment by Dpeta** [comment]
Seems to work now :3 👍

![Screenshot 2022-06-29 050608](https://user-images.githubusercontent.com/69427753/176342557-dda3a34f-47a8-495a-8ad4-a89e4dac108f.png)
