### ISSUE TITLE
My username is taken?

### ISSUE THREAD

**Issue by WellDressedRat** [Dpeta/pesterchum-alt-servers#67]
Any time I try to get back into pesterchum, it says my username is taken. I did see on the faq that you do have to fully close the application for it to work, but I have been and it still won't work, it's also not running according to task manager. I think I may have messed it up by moving the application to my desktop for easy access. When I did that, it stopped working (would give me an error saying I should try redownloading it to get it to work) and I struggled for a bit to get it working, but eventually another pesterchum application appeared in the folder that I could actually use, which I think where the problem is. Any time I try to delete the version of the application that won't work, it says that it's running and I can't delete it. I think it might fix if I could figure out how to full delete it and redownload it but until then, is there another fix to this issue?

**Comment by Dpeta** [comment]
If it says it's still running then it's probably still running, if you can't find the program in task manager maybe restart your pc :0
Alternatively just message a mod on discord or pchum and ask one of us to kick you off your handle, I'm usually on ``Shou`` recently.
