### ISSUE TITLE
Unable to run Mac version

### ISSUE THREAD

**Issue by TophatE** [Dpeta/pesterchum-alt-servers#73]
Of course, once again, the pain sets in as I can not figure out how to run the mac version with python, and using the command in the installation leaves me with an error that no Pesturchum.py file exists.

saddddd

**Comment by Dpeta** [comment]
Assuming the command you mean is ``python3 pesterchum.py``, that's for running from source. You can just download the source code option assuming you have Python and Pesterchum's dependencies.
To actually try to run the mac build you just need to open the file called "pesterchum".

**Comment by Dpeta** [comment]
The mac build does seem to be broken again though </3

**Comment by TophatE** [comment]
Unfortunately yeah. . The pesturchum file is actually a document file, so opening it just opens textedit sadly.

**Comment by Dpeta** [comment]
It is definitely an executable, not sure why that's the default file association

**Comment by Dpeta** [comment]
Regardless of the build though, you should just be able to run from source if you already have Python, just do something like:
1. Download and extract https://github.com/Dpeta/pesterchum-alt-servers/archive/refs/tags/v2.2.zip (source code)
2. Run ``python3 -m pip install pygame PyQt5 feedparser python-magic requests`` to install the dependencies.
3. Run ``cd /folder/`` to move the terminal to the folder where you extracted the zip.
4. Run ``python3 pesterchum.py`` or just ``pesterchum.py``

**Comment by TophatE** [comment]
The new build WORKS! Let's GOOOO! Tysm!

**Comment by Dpeta** [comment]
![SCrainbowdance](https://user-images.githubusercontent.com/69427753/160056106-06c58d8f-db8e-4c1c-b487-95e2c657e223.gif)
