### ISSUE TITLE
Pesterchum wont launch in wayland

### ISSUE THREAD

**Issue by LithRakoon** [Dpeta/pesterchum-alt-servers#76]
continuation on #75

all my testing is done on KDE plasma with their implementation of wayland
with AMD graphics
fedora 35

the output i get when launching Pesterchum in wayland from the native build
<code> Usage: pesterchum.py [OPTIONS]
Use -h/--help to see the available options.
Logging is configured in logging.ini
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
./Pesterchum: symbol lookup error: /lib64/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags</code>

but running from source everything works in wayland
<code>Usage: pesterchum.py [OPTIONS]
Use -h/--help to see the available options.
Logging is configured in logging.ini
</code>
no errors

related issues could be:
https://github.com/kovidgoyal/kitty/issues/4760
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005268;msg=19

**Comment by Dpeta** [comment]
Still can't reproduce this, seems to work with the latest Fedora 35 iso. Could you post your dnf info output for mesa-libEGL and libwayland-client? :?c

**Comment by LithRakoon** [comment]
<code>sudo dnf info libwayland-client
Last metadata expiration check: 0:00:37 ago on Thu 14 Apr 2022 01:39:55 PM.
Installed Packages
Name         : libwayland-client
Version      : 1.20.0
Release      : 4.fc35
Architecture : i686
Size         : 57 k
Source       : wayland-1.20.0-4.fc35.src.rpm
Repository   : @System
From repo    : updates
Summary      : Wayland client library
URL          : http://wayland.freedesktop.org/
License      : MIT
Description  : Wayland client library

Name         : libwayland-client
Version      : 1.20.0
Release      : 4.fc35
Architecture : x86_64
Size         : 66 k
Source       : wayland-1.20.0-4.fc35.src.rpm
Repository   : @System
From repo    : updates
Summary      : Wayland client library
URL          : http://wayland.freedesktop.org/
License      : MIT
Description  : Wayland client library
</code>

<code>
sudo dnf info mesa-libEGL
Last metadata expiration check: 0:01:18 ago on Thu 14 Apr 2022 01:39:55 PM.
Installed Packages
Name         : mesa-libEGL
Version      : 23.0.0
Release      : git.20220403.c4650cb.fc35
Architecture : i686
Size         : 418 k
Source       : mesa-23.0.0-git.20220403.c4650cb.fc35.src.rpm
Repository   : @System
From repo    : nobara-mesa-git-i386
Summary      : Mesa libEGL runtime libraries
URL          : http://www.mesa3d.org
License      : MIT
Description  : Mesa libEGL runtime libraries.

Name         : mesa-libEGL
Version      : 23.0.0
Release      : git.20220403.c4650cb.fc35
Architecture : x86_64
Size         : 421 k
Source       : mesa-23.0.0-git.20220403.c4650cb.fc35.src.rpm
Repository   : @System
From repo    : nobara-mesa-git
Summary      : Mesa libEGL runtime libraries
URL          : http://www.mesa3d.org
License      : MIT
Description  : Mesa libEGL runtime libraries.
</code>

**Comment by Dpeta** [comment]
nobara-mesa-git looks like third-party repository, maybe this is an issue with their binaries?

**Comment by Dpeta** [comment]
The official repository only provides [21.3.8-2.fc35](https://packages.fedoraproject.org/pkgs/mesa/mesa-libEGL/) for Fedora 35, there doesn't actually even seem to be any release scheduled with "23" as its version yet? There's [no tag](https://gitlab.freedesktop.org/mesa/mesa/-/tags) and it's not on mesa's [release calendar](https://docs.mesa3d.org/release-calendar).

**Comment by LithRakoon** [comment]
its the repo provided by nobara for a better gaming experience, i am talking to the creator of it to see whats wrong ill update you once more information is provided

**Comment by LithRakoon** [comment]
hello!
sorry for the late response ive had a busy few days.

after talking to creator i have some info, the nobara repo of mesa is built and updated regularly (every few weeks to a month on average), and there must have been a breaking change which breaks on older versions of mesa.
the only fix to this is building against latest mesa, but this could mean older versions of mesa wont work (not tested just a hypothetical).
so i understand if this will stay unfixed for now

**Comment by Dpeta** [comment]
That seems likely then, yeah

There's already a release build against a pretty recent mesa version, the glibc2.35+ build, which is build on [Arch](https://archlinux.org/packages/extra/x86_64/mesa/). That one probably won't run on your system though since you presumably still have glibc 2.34.

I think making a build for this would require making a build for Fedora 35 + Nobara specifically, to accommodate both the glibc and mesa package versions. Since that's a pretty specific (& unsupported) setup it doesn't really seem worth the effort to make releases for it rn though, especially since running from source is just better in every way anyway :"3 :+1: 

\+ seems like Fedora 36 is about to come out of beta, might work there since it has glibc2.35 :3
