### ISSUE TITLE
says one of my handles is taken despite it just being mine

### ISSUE THREAD

**Issue by mortismordecai** [Dpeta/pesterchum-alt-servers#77]
hi, sorry made a github account entirely to report this issue so sorry if i'm a bit awkward
but basically, i made a chum handle earlier today, went to set it as my default, i closed pesterchum for maybe an hour and when i reopened it and try to use said handle, it says it is taken already? i don't understand as it doesn't give this message for any of my other handles, and it is not a canon handle(at least not that im aware of) is there anything i can do to fix this?

**Comment by Dpeta** [comment]
Either Pesterchum was still open in the background or someone else was on the handle probably, you could always message it & see if you convo window pops up :0, if it does, check your system tray or maybe close pchum with task manager.

Or alternatively just msg any mod that's online or @ a mod in one of the discords & ask them if they can kick the handle :3 :+1:
