### ISSUE TITLE
Cant get it to run on my computer

### ISSUE THREAD

**Issue by radTad15** [Dpeta/pesterchum-alt-servers#8]
Hello!
When I try to launch Pesterchum and try to select a server, it gives me this error:
![image](https://user-images.githubusercontent.com/21113698/98496792-0a21c480-2208-11eb-8119-2c4590507db7.png)
(Same for each server I try)

How can I fix this?

Thank you!!!!

**Comment by Dpeta** [comment]
Hi! Sorry for my late response. I'm not entirely sure why it isn't able to access the file, but the way I implemented that was beyond horrible anyway so it's not surprising that it was causing issues.
It's no longer used in the most recent release, so hopefully that one will work.
