### ISSUE TITLE
Unable to Run

### ISSUE THREAD

**Issue by TheNixSys** [Dpeta/pesterchum-alt-servers#81]
I downloaded the Zip file, And i'm assuming it was the correct one, But whenever I try to open it it shows me this and gives me no option to run it otherwise.
![image](https://user-images.githubusercontent.com/107083789/172500632-794506a2-c602-44bf-bd78-28d075e2dc44.png)

**Comment by Dpeta** [comment]
Yeah; my executables aren't signed by any authority, so they're unrecognized & you gotta press "more info" --> "run anyway". Seems like you figured that out though :"3

A way to avoid the message completely is to generate your own [executable/build from source](https://github.com/Dpeta/pesterchum-alt-servers#freeze--build).
