### ISSUE TITLE
after X'ing out i cant use the same name

### ISSUE THREAD

**Issue by jamer1870** [Dpeta/pesterchum-alt-servers#83]
when Xing out and going back in it never lets me use my prev name

**Comment by Dpeta** [comment]
Pesterchum was probably just minimized to your tray, that's when happens when you press the 'x´, you gotta do client --> exit to shut it down fully.  

Alternatively just msg me on 'Shou' or in the discord & I can just kick the old session if you want :"3

**Comment by Leach7517** [comment]
Same

**Comment by Dpeta** [comment]
If Pesterchum is still running in the background, close it from the tray or with task manager.
