### ISSUE TITLE
hello, sorry, i have a problem and i idk who to contact 

### ISSUE THREAD

**Issue by May-ops** [Dpeta/pesterchum-alt-servers#85]
umh. as i said, i have a problem. this problem sounds\looks like 
"f41l3d: closing link: [my nickname] [some numbers]
(registration timeout)" 
And, so, i really dont know what to do. I can not do anything: can't change my nickname, I can't change my account, I can't do anything, absolutely nothing

I really apologize if I wrote somewhere in the wrong place. I'm pretty bad at English, so I also apologize for this clumsy auto-translation. thanks in advance for any answer

**Comment by Dpeta** [comment]
Generally registration timeout happens when a client successfully connects, but then takes too long to send its handle and other info to the server.

Seems like a socket-related bug? Since it says your nick presumably either ``USER`` failed to send, it had incorrect syntax, or the client failed to respond to the server's ping during the registration. I can't reproduce that though so I'm not sure why that'd be happening;

Maybe try going back to v2.2.3 for now? That release seems to have less socket issues.

**Comment by May-ops** [comment]
> Generally registration timeout happens when a client successfully connects, but then takes too long to send its handle and other info to the server.
> 
> Seems like a socket-related bug? Since it says your nick presumably either `USER` failed to send, it had incorrect syntax, or the client failed to respond to the server's ping during the registration. I can't reproduce that though so I'm not sure why that'd be happening;
> 
> Maybe try going back to v2.2.3 for now? That release seems to have less socket issues.


Thanks a lot for your answer. I will try another version as you advised. Maybe it's because of my bad internet connection (unfortunately, i have no way yet to change it), maybe it's because the new version. I can add that the program downloaded from this link (https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.3) worked until the error appeared. In the next version (https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.3.1) the error persisted. As I said, I'll really try to use the old version.
However... May I know if it is possible to install the program from scratch? I mean, when I downloaded its new version and deleted the old one, the old settings were saved: my profile, quirk and others. Perhaps if you install everything from scratch, the error will disappear. The data listed above will also be deleted, but the program will at least run

**Comment by Dpeta** [comment]
Bad internet connection could be a reason for the timeout :0c
If you're on Windows then data like profile/quirks/logs is stored in appdata/local/pesterchum, you could move the 'pesterchum' folder somewhere else temporarily to try running it from scratch, it wouldn't require permanently deleting anything.
Something else you could maybe try is manually adding "irc.pesterchum.xyz:6667" as a server without SSL/TLS, that'll be less secure but also require one less handshake for a connection.

**Comment by May-ops** [comment]
I'll try everything we talked about. Thank you for your reply

**Comment by Dpeta** [comment]
Did you end up getting it working? :0c
