### ISSUE TITLE
trouble downloading 

### ISSUE THREAD

**Issue by isorib** [Dpeta/pesterchum-alt-servers#86]
i have a windows10 64 bit 
ive downloaded github desktop but im not sure on how to download pesterchum itself. im very unfamiliar with github, as ive never used it before so this is all new to me. 
any help with downloading it and navigating through it would be extremely useful for me :33
thanks!

**Comment by Dpeta** [comment]
Howdy :0

Github desktop is for git/development, you don't need it to install Pesterchum ;w;

The binary downloads are on the releases page: https://github.com/Dpeta/pesterchum-alt-servers/releases
the version you probably want is this one 👇👇👇
![Screenshot_20220713_231549](https://user-images.githubusercontent.com/69427753/178837605-59654307-9e5d-415e-ac91-01de9487c3a5.png)
