### ISSUE TITLE
failed to load pesterchum

### ISSUE THREAD

**Issue by zippofuel** [Dpeta/pesterchum-alt-servers#87]
so i downloaded pesterchum, extracted the zip files and ran the executable but the app wont open and just says "failed to load pesterchum.js, this might require manual intervention: consider overriding C:/Users/#####/AppData/Local\pesterchum/
with a backup: C:/Users/#####/AppData/Local\pesterchum/backup
was wondering if anyone could help me out, I did hear servers shut down but idk if that's true to be honest, just want some help

**Comment by Dpeta** [comment]
Seems like it can't load pesterchum.js for some reason, if this is your first time running pchum it's safe to just delete C:/Users/#####/AppData/Local\pesterchum/ entirely & it'll remake it.

ghostDunk's server (mindfang) shut down two years ago, this pchum connects to pesterchum.xyz instead.

**Comment by zippofuel** [comment]
where should i find C:/Users/#####/AppData/Local\pesterchum/ i have no idea where it is

**Comment by zippofuel** [comment]
hey bro, i figured it out, theres no problem anymore, pesterchum works for me now
