### ISSUE TITLE
Problems with signing back in

### ISSUE THREAD

**Issue by Noodllen** [Dpeta/pesterchum-alt-servers#90]
I guess im not the only one having this problem so i figured id ask about it. 
Each time i try to sign back into my original handle (that i had created and used only on my main pc), after i had closed the app the other day, it says that the handle is already taken. 
I had it set to default when i had made it so im not sure why it did this to me. 

vv image refence vv
![Screenshot 2022-08-25 142007](https://user-images.githubusercontent.com/112117324/186740045-89aa9185-5969-45c1-9b54-4223e12e682a.jpg)

Edit: I figured id mention that when i hit the "choose existing profile" section, the option to choose my account is there by it still says that the account is taken

**Comment by Dpeta** [comment]
That means that handle is already taken, only one client can be on a handle at the same time. Either another instance of Pesterchum is still open in the background, or someone's signed into the handle on another pc. Maybe check your taskbar or alternatively close it with task manager if there's another instance on your pc.

**Comment by Dpeta** [comment]
I've kicked the handle 4 now so hopefully that takes care of that :"3

**Comment by Noodllen** [comment]
> I've kicked the handle 4 now so hopefully that takes care of that :"3

that fixed it!!! thanks so much!!

**Comment by Dpeta** [comment]
🐈🎉🎉🎉🎉
