### ISSUE TITLE
quirk issue?

### ISSUE THREAD

**Issue by DollFaceMcGhost** [Dpeta/pesterchum-alt-servers#92]
![issue](https://user-images.githubusercontent.com/112598155/187816281-c62f0013-e8b8-4d85-abd2-cecde8303bd4.png)
I'm honestly not entirely sure what this means, it just pops up when I try to make a simple replace typing quirk. I've tried a couple of times, after closing and restarting the program and trying different combinations to see if it was just the specific quirk I was trying. That pop up is all I've been getting and I'm honestly hoping it's just a user error that I can get to the bottom of and stop doing. Thanks in advance for help or suggestions!

**Comment by Dpeta** [comment]
Should hopefully be fixed now for the next release https://github.com/Dpeta/pesterchum-alt-servers/commit/b549645a50fc316e8d46aa3731ffa203ba47839a :"3

**Comment by DollFaceMcGhost** [comment]
Thank you so much, I really appreciate it!

**Comment by Dpeta** [comment]
🐈🎉

Should be fixed now with [2.4.3](https://github.com/Dpeta/pesterchum-alt-servers/releases/tag/v2.4.3)
