### ISSUE TITLE
"(user) did not receive message"

### ISSUE THREAD

**Issue by the-dreemurrs** [Dpeta/pesterchum-alt-servers#94]
so i have two accounts im working with trying to get them to communicate across two different computers just to mess around and try things out, but i cant seem to get them to actually be able to communicate. regardless of who is logged in on which computer, computer A will not receive any messages from computer B. this isnt the case with other profiles, im not sure whats going on, if i log out of one of the profiles then both computers can communicate fine, but these specific profiles just refuse to cooperate. 

im running the mac build, one computer is running macOS 12.4 and the other is running macOS 10.14.6, which is the one having trouble. im not sure how id be able to provide debug logs for this? is it possible im having issues because one of the computers is still on mojave?

**Comment by Dpeta** [comment]
Are you certain you're messaging the correct handles? I'm not aware of any bug that'd just cause a message to not appear.

Mojave ought to work, it's the OS version I build the latest release on.

If there's any error logs they'll be in the hidden ``.pesterchum/errorlogs/`` folder in your home directory, but exceptions like that should ideally also create a popup error, so I don't think that'll be helpful here.

If you're actually seeing the ``-- aA [AA] did not receive message from bB [BB] at 00:00 --`` message specifically, and not just silently not receiving a message, then that probably means one of the computers has the other handle blocked.

**Comment by the-dreemurrs** [comment]
ill check it again but im fairly certain ive got them right. i highly doubt either one has the other handle blocked considering which one can actually send messages changes depending on which computer is logged into which. 

if i have aA on the mojave computer and bB on the monterey computer, bB wont receive anything from aA but aA will receive messages from bB, but if i log into bB on mojave and aA on monterey, then account aA wont receive anything from bB while bB does receive messages from aA. 

DD is on the monterey computer, while WW is on the mojave computer. both handles are registered to me and neither one is blocked. 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/69612650/191379556-0344e2b5-9de3-433a-a01e-724a2407f906.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/69612650/191379526-5511f84a-3724-48ca-a640-c5d9f02ea203.png">

and now swapped, WW is on monterey while DD is on mojave.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/69612650/191380100-9949e143-46b9-4f30-9708-12dc79cc042a.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/69612650/191380139-011b53bf-e02d-47b0-8187-4cab08263cd9.png">

**Comment by Dpeta** [comment]
"did not receive message from" is a message that should only appear when a handle is blocked, it's a theme defined string ([search](https://github.com/Dpeta/pesterchum-alt-servers/search?q=did+not+receive+message)) that is only shown when a user has the other blocked. ([convo.py](https://github.com/Dpeta/pesterchum-alt-servers/blob/ef0898e8c7f4ef148c0e591db325963dad74a157/convo.py#L458))

Maybe double/triple check your full blocklist/trollslum? It's under the profile tab.

**Comment by the-dreemurrs** [comment]
oh my god i could have sworn they werent blocked but i forgot the blocklist was called the trollslum, that did it, thanks!

**Comment by Dpeta** [comment]
🐈🎉
