### ISSUE TITLE
"Server certificate validation failed", Cant connect?

### ISSUE THREAD

**Issue by arcaneAnthropos** [Dpeta/pesterchum-alt-servers#96]
hello! if this is an obvious problem I apologize, i'm not exactly a computer whiz. I just downloaded the mac zip of pesterchum and got this error: 
<img width="717" alt="Screen Shot 2022-09-26 at 5 58 43 PM" src="https://user-images.githubusercontent.com/114453128/192407345-895f7237-1f63-4f8b-8077-fb0cbd81f0ac.png">
i'm using mac os monterey, btw. i have pretty stable internet and most of my software is up to date? all I did to the file was move the application itself to my "applications" folder so it was easier to access. 
is there any way to fix this? thanks so much!

**Comment by Dpeta** [comment]
Seems like the system-provided SSL library on MacOS is outdated, so Python's SSL module doesn't use the system's root certificates: https://github.com/python/cpython/issues/72337#issuecomment-1093726723

I'm not sure what the proper way to mitigate this would be, I could possibly include a root certificate bundle like certifi with the MacOS version specifically, but that has the potential to get outdated pretty quickly.

For now I think [installing a recent version of Python](https://www.python.org/downloads/) and then installing the certificates like is demonstrated [here](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate) ought to provide the required certificates. Unless you're particularly concerned about security just ignoring the error is fine though.

**Comment by arcaneAnthropos** [comment]
thanks so much for your help! this worked fine :) i was so worried I wasn't going to be able to use your wonderful application and i'm so glad it operates now ^_^

**Comment by FlamboyantMisfit** [comment]
hi i ran into the same issue on windows 10 version, would i do the same as above? im not very tech savvy ;~; 
![image](https://user-images.githubusercontent.com/25468912/195449752-aeb9decc-88c0-41cd-a6de-fe164857dd12.png)

**Comment by Dpeta** [comment]
🐈🎉

Put up a MacOS test build with certifi, hopefully that lets pchum validate certs on mac until the build gets really outdated: https://github.com/Dpeta/pesterchum-alt-servers/releases/download/v2.5-rc.1/PesterchumAlt.-2.5-rc.1-mac64-macosx10.14+.zip

Would be helpful if a Mac user without python certs installed could verify if that fixes the warning

**Comment by Dpeta** [comment]
Someone in the discord confirmed the certifi build works, so this issue ought to be solved now.
